# Generated by Django 4.2 on 2023-04-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
