# Generated by Django 4.2 on 2023-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0002_alter_modalidade_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome'], 'verbose_name': 'modalidade', 'verbose_name_plural': 'modalidade'},
        ),
        migrations.RenameField(
            model_name='modalidade',
            old_name='id_modalidade',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modalidade',
            old_name='nome_modalidade',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='modalidade',
            name='local',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='modalidade',
            table='modalidade',
        ),
    ]
