# Generated by Django 4.2.13 on 2024-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0003_alter_modalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome'], 'verbose_name': 'modalidade', 'verbose_name_plural': 'modalidades'},
        ),
    ]
