# Generated by Django 4.2 on 2023-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=256)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=256)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'campeonato',
                'verbose_name_plural': 'campeonatos',
                'db_table': 'campeonato',
                'ordering': ['nome'],
            },
        ),
    ]
